version: "3"

services:
  node:
    container_name: node
    build:
      context: ./node
    command: npm run start
    volumes:
      - /app/node_modules
      - ./node:/app
    ports:
      - "8000:80"

  nginx:
    # container_name: nginx
    image: nginx:1.15.3
    volumes:
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "8081:80"
    # environment:
    #   - NGINX_HOST=foobar.com
    #   - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
